# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

perm_test <- function(logarithm, P, N_breaks, cluster_ids, n_clusters, sample_ids, n_samples, group_ids_of_samples, min_counts_per_group, group_ids, counts, nCores) {
    .Call(`_discerner_perm_test`, logarithm, P, N_breaks, cluster_ids, n_clusters, sample_ids, n_samples, group_ids_of_samples, min_counts_per_group, group_ids, counts, nCores)
}

perm_test_MG_baseline <- function(logarithm, P, N_breaks, cluster_ids, n_clusters, sample_ids, n_samples, group_ids_of_samples, min_counts_per_group, n_samples_per_group_per_sample, counts, n_groups) {
    .Call(`_discerner_perm_test_MG_baseline`, logarithm, P, N_breaks, cluster_ids, n_clusters, sample_ids, n_samples, group_ids_of_samples, min_counts_per_group, n_samples_per_group_per_sample, counts, n_groups)
}

perm_samples_test <- function(logarithm, P, N_breaks, cluster_ids, n_clusters, sample_ids, n_samples, group_ids_of_samples, min_counts_per_group, group_ids, counts) {
    .Call(`_discerner_perm_samples_test`, logarithm, P, N_breaks, cluster_ids, n_clusters, sample_ids, n_samples, group_ids_of_samples, min_counts_per_group, group_ids, counts)
}

